### ISSUE TITLE
CID/CIA translation in generateImpactsAppreciation

### ISSUE THREAD

**Issue by b4stet** [monarc-project/zm-client#3]
https://github.com/monarc-project/zm-client/blob/a905e049744a0eea3e170c7479452e5c63fee351/src/MonarcFO/Service/DeliverableGenerationService.php#L1469

Hi,
The mentioned method is used to generate deliverable #2 Context Modelling.
At this line, ucfirst($impact) may need to be translated, otherwise every languages will get 'D' for availability in the table.

If you confirm, I tested and one solution to get CID/CIA accordingly is to replace L1469 by:
```
$translatedImpact = ucfirst($impact);
if ($impact === 'd'){
     $translatedImpact = ucfirst($this->anrTranslate('A'));
}
$table->addCell(\PhpOffice\Common\Font::centimeterSizeToTwips(1.00), $cellRowSpan)->addText($translatedImpact, $styleContentFontBold, $alignCenter);
```

**Comment by cedricbonhomme** [comment]
Nice catch, this will indeed fix the problem.
Feel free to make a PR. Or if you prefer I can commit this.
Thank you
